---
# handlers file for roles/docker
- name: pull api image
  docker_image:
    name: cyrus925/tp1-backend
    tag: latest
    source: pull  
  vars:
      ansible_python_interpreter: /usr/bin/python3

- name: Run api container
  docker_container:
    name: backendcontainer
    image: cyrus925/tp1-backend
    networks: 
      - name: "app-network"
    state: started
  vars:
      ansible_python_interpreter: /usr/bin/python3
