name: CI devops 2024
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
  pull_request:

jobs:
  build-and-test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - name: Checkout code
        uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution : 'temurin'
          java-version: '17'
        #TODO

     #finally build your app with the latest command
      - name: Build and test with Maven
        #run: cd backend/simple-api-student && mvn clean verify
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=tpdevopsdecyrus_tp-dev-ops -Dsonar.organization=tpdevopsdecyrus -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file backend/simple-api-student/pom.xml
# Define job to build and publish Docker image

  build-and-push-docker-image:
    needs: build-and-test-backend
    # Run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # Steps to perform in job
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # Relative path to the place where source code with Dockerfile is located
          context: ./backend/simple-api-student
          # Note: tags have to be all lower-case
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}
        

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}
        

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}


    
  connect-to-the-vm:
    needs:  build-and-push-docker-image
    # Run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # Steps to perform in job
    steps:
       - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
        
      - name: Run ansible
        run: ansible-playbook -i inventories/setup.yml playbook.yml
